"""Beam search over a synthetic token tree.

A real LLM beam search needs per-token logprobs and many API calls. For
pedagogy we use a deterministic, hand-tuned probability tree so the algorithm
is the star, not the API plumbing. Each node has a token and a probability
conditioned on its parent.

The trace records, step by step:
- the current beam set (sequences kept alive),
- the candidates generated by expanding each beam (cartesian product),
- which were kept and which were pruned.
"""
from __future__ import annotations

import math
from dataclasses import dataclass

# Conditional probability tree. Each level has the same set of children per parent
# for simplicity. Probabilities are hand-tuned so beam matters.
# Layer 0 (root) -> token list with (token, prob)
TREE: dict[str, list[tuple[str, float]]] = {
    "<s>":       [("the", 0.55), ("a", 0.30), ("our", 0.10), ("my", 0.05)],
    "the":       [("cat", 0.40), ("dog", 0.30), ("model", 0.20), ("agent", 0.10)],
    "a":         [("cat", 0.35), ("dog", 0.35), ("model", 0.20), ("idea", 0.10)],
    "our":       [("model", 0.50), ("agent", 0.40), ("plan", 0.10)],
    "my":        [("cat", 0.50), ("dog", 0.40), ("model", 0.10)],
    "cat":       [("sat", 0.55), ("ran", 0.25), ("slept", 0.20)],
    "dog":       [("ran", 0.55), ("sat", 0.30), ("barked", 0.15)],
    "model":     [("learned", 0.50), ("failed", 0.30), ("trained", 0.20)],
    "agent":     [("solved", 0.55), ("planned", 0.30), ("looped", 0.15)],
    "idea":      [("worked", 0.60), ("failed", 0.40)],
    "plan":      [("worked", 0.55), ("failed", 0.45)],
    "sat":       [("on", 0.70), ("down", 0.30)],
    "ran":       [("away", 0.50), ("fast", 0.50)],
    "slept":     [("on", 0.60), ("through", 0.40)],
    "barked":    [("loud", 0.55), ("twice", 0.45)],
    "learned":   [("a", 0.55), ("the", 0.45)],
    "failed":    [("the", 0.60), ("at", 0.40)],
    "trained":   [("on", 0.70), ("for", 0.30)],
    "solved":    [("the", 0.65), ("a", 0.35)],
    "planned":   [("a", 0.60), ("for", 0.40)],
    "looped":    [("forever", 0.60), ("briefly", 0.40)],
    "worked":    [("well", 0.65), ("poorly", 0.35)],
}


def next_tokens(tok: str) -> list[tuple[str, float]]:
    return TREE.get(tok, [])


@dataclass
class Beam:
    seq: list[str]
    logp: float


def search(beam_width: int = 3, max_steps: int = 5) -> dict:
    beams = [Beam(seq=["<s>"], logp=0.0)]
    steps: list[dict] = []

    for step in range(max_steps):
        candidates: list[Beam] = []
        per_beam: list[dict] = []
        for b in beams:
            last = b.seq[-1]
            nxt = next_tokens(last)
            children = []
            for tok, p in nxt:
                lp = b.logp + math.log(p)
                cand = Beam(seq=b.seq + [tok], logp=lp)
                candidates.append(cand)
                children.append({"token": tok, "p": p, "logp_after": round(lp, 3)})
            per_beam.append({"seq": list(b.seq), "logp": round(b.logp, 3), "expansions": children})

        if not candidates:
            steps.append({"step": step + 1, "expansions": per_beam, "kept": [], "pruned": [], "reason": "no continuations available; stopping."})
            break

        candidates.sort(key=lambda c: -c.logp)
        kept = candidates[:beam_width]
        pruned = candidates[beam_width:]

        steps.append({
            "step": step + 1,
            "expansions": per_beam,
            "kept": [{"seq": k.seq, "logp": round(k.logp, 3)} for k in kept],
            "pruned": [{"seq": p.seq, "logp": round(p.logp, 3)} for p in pruned[:8]],
            "reason": f"expanded {len(beams)} beams into {len(candidates)} candidates; kept top {beam_width} by logprob",
        })
        beams = kept

    # final best
    best = max(beams, key=lambda b: b.logp) if beams else None
    return {
        "beam_width": beam_width,
        "max_steps": max_steps,
        "steps": steps,
        "best": {"seq": best.seq, "logp": round(best.logp, 3)} if best else None,
    }
